server:
  port: 9191

spring:
  application:
    name: SpringOpenAI
  ai:
    google:
      genai:
        api-key: ${googleAI_Key}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.7
    openai:
      api-key: ${openAI_Key}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.6



